encyclopedia/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

urlpatterns = [
    path("", views.index, name="index"),
    # path("a/", views.viewz, name="viewz")
    path("wiki/<str:TITLE>", views.content, name="content"),
    path("wiki/new/add/", views.addcontent, name="add"),
    path("wiki/new/rand/", views.rand, name="rand"),
    path("wiki/new/edit/<str:TITLE>", views.editz, name="edit"),
    path("wiki/new/saveedit", views.saveedit, name="saveedit"),
    # path("wiki/search/<str:searchkeyword>", views.search, name="searchkeyword"),
    # path("wiki/search/<str:q>", views.search, name="s")
    url(r'^wiki/search/$', views.search, name="s")


    

]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf import settings

from django.views.static import serve
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"),),
    url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}), 
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from django.shortcuts import render
import markdown2
from . import util
from django.http import HttpResponse 
from django.http import HttpResponseRedirect
from django.utils.safestring import mark_safe
from . import urls
from django.urls import reverse
from django import forms
import random
# from django.urls import redirect
def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })

def content(request, TITLE):
    
    return render(request, "encyclopedia/showcontent.html",{
        "content": markdown2.markdown(util.get_entry(TITLE)),
        "title": TITLE
    })

# def search(request, searchkeyword):
#     stored_entries = util.list_entries()
#     ls = []
#     for entry in stored_entries:
#         if searchkeyword.lower() == entry.lower():
#             # url = urls.urlpatterns.name['index']
#             s = reverse('content', args=[searchkeyword])
            
#             return HttpResponseRedirect(s)

#             # return redirect(views.index)
            
#         else:
#             a = entry.lower()
#             z = a.find(searchkeyword)
            
#             if (z >-1):
#                 ls.append(entry)
                


def search(request):
    q = request.GET.get('q')
    
    stored_entries = util.list_entries()
    ls = []
    for entry in stored_entries:
        if q.lower() == entry.lower():
            # url = urls.urlpatterns.name['index']
            s = reverse('content', args=[q])
            
            return HttpResponseRedirect(s)

            # return redirect(views.index)
            
        else:
            a = entry.lower()
            z = a.find(q)
            
            if (z >-1):
                ls.append(entry)

 
    
    if len(ls) == 0:
        return render(request, "encyclopedia/notfound.html")
    else:
        return render(request, "encyclopedia/search.html", {
        "entries": ls
        
    })


# def s(request):
#      try:
#         q = request.GET.get('q')
#     return HttpResponseRedirect




# def viewz(request):
#     temp = util.get_entry("Git")
    
#     return render(request, "encyclopedia/temp.html", {
#         "entries": markdown2.markdown(mark_safe(temp))
#     })
    

    # mark safe ki jagha html template me use kiya hu sfe and autoescape off
    

class newcontentform(forms.Form):
    title = forms.CharField(label="Title")
    # content = forms.CharField(label="content")
    content = forms.CharField(widget=forms.Textarea, label="content")

# def addcontent(request):
#     if request.method == "POST":
#             newcontent = form.cleaned_data["content"]
#             newtitle = form.cleaned_data["title"]
#             util.save_entry(newtitle, newcontent)
#             s = reverse('content', args=[newtitle])
#             return HttpResponseRedirect(s)
#     return render(request, "encyclopedia/form.html", {
#         "form": newcontentform()
#         })


def addcontent(request):
    if request.method == "POST":
        z = request.POST
        newcontent = z["content"]
        newtitle = z["title"]
        for entry in util.list_entries():
            if entry == newtitle:
                return render(request, "encyclopedia/error.html",{
                    "content": "This content already exist",
                    "address": reverse('content', args=[newtitle]),
                    "title": newtitle
                })
        util.save_entry(newtitle, newcontent)
        s = reverse('content', args=[newtitle])
        return HttpResponseRedirect(s)
    return render(request, "encyclopedia/form.html", {
        "form": newcontentform()
        })

def rand(request):
    a = util.list_entries()
    
    z = str(random.choice(a))
    return render(request, "encyclopedia/showcontent.html",{
        "content": markdown2.markdown(util.get_entry(z)),
        "title": z
    })



def saveedit(request):
    if request.method == "POST":
        z = request.POST
        newcontent = z["content"]
        newtitle = z["title"]
        
        util.save_entry(newtitle, newcontent)
        s = reverse('content', args=[newtitle])
        return HttpResponseRedirect(s)
    



def editz(request, TITLE):
    a=util.get_entry(TITLE)
    
    return render(request, "encyclopedia/edit.html",{
        "content": util.get_entry(TITLE),
        "title": TITLE
    })

encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}
{% block style %}
<style>

#id_title {
    
    margin: 10px;
    margin-right: 23em;
}
/* #id_title::after {
    content: "\a";
    white-space: pre;
} */

label {
    
    margin-left: 111px;
}


/* label:nth-child(1) {
    margin-left: 76px;
    background: red;
} */
#divtwo{
    display: flex;
    /* justify-content: center; */
    align-items: center;
    margin: 5px;
    margin-top: 20px;
}
#secondlabel{
    margin-left: 10px;
}
#id_content{
    height: 149px;
}
#button{
    display: block;
    margin-left: 10px;
    
}
</style>
{% endblock %}

{% block body %}
    <h1>hello</h1>
    <div>
    <form action="{% url 'saveedit' %}" method="POST">
        {% csrf_token %}
        <label for="id_title">Edit Title:</label>
        <input type="text" name="title" required="" id="id_title" value="{{title}}">
        <br>
        <div id="divtwo">
            <label for="id_content" id="secondlabel">Edit content:</label>
            <textarea name="content" cols="400" rows="10" required="" id="id_content" spellcheck="false">{{content}}</textarea>
            <input type="submit" value="save" id="button"> 
        </div>
    </form>
   </div>
{% endblock %}

encyclopedia/templates/encyclopedia/error.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}


{% block body %}
    

    <div>
        <h1>{{ content }}</h1>
        <P> <a href="{{address}}"> go to {{title}} Page </a> </P>
    </div>

{% endblock %}

encyclopedia/templates/encyclopedia/form.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}
{% block style %}
<style>

#id_title {
    
    margin: 10px;
    margin-right: 23em;
}
/* #id_title::after {
    content: "\a";
    white-space: pre;
} */

label {
    
    margin-left: 111px;
}


/* label:nth-child(1) {
    margin-left: 76px;
    background: red;
} */
#divtwo{
    display: flex;
    /* justify-content: center; */
    align-items: center;
    margin: 5px;
    margin-top: 20px;
}
#secondlabel{
    margin-left: 10px;
}
#id_content{
    height: 149px;
}
#button{
    display: block;
    margin-left: 10px;
    
}
</style>
{% endblock %}

{% block body %}
    <h1>hello</h1>
    <div>
    <form action="{% url 'add' %}" method="POST">
        {% csrf_token %}
        <label for="id_title">Title:</label>
        <input type="text" name="title" required="" id="id_title">
        <br>
        <div id="divtwo">
            <label for="id_content" id="secondlabel">content:</label>
            <textarea name="content" cols="400" rows="10" required="" id="id_content" spellcheck="false"></textarea>
            <input type="submit" value="save" id="button"> 
        </div>
    </form>
   </div>
{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}


{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            
             

        <a href="wiki/{{entry}}"> <li>{{ entry }}</li> </a>

        {% endfor %} 
    </ul>
    <!-- <iframe width="800" height="450" src="https://www.youtube.com/embed/t0YtIiwKPC0?list=PLhSp9OSVmeyKVpGhYpSMkSkbohXDMrrHO" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe> -->
{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        {% block style %}{% endblock %}
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
        <style>
            body{
                    position:fixed;
                    top:0;
                    bottom:0;
                    left:0;
                    right:0;
                }
        </style>
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 's' %}" method="GET"> 
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'add' %}"> Create New Page </a>
                </div>
                <div>
                    <a href="{% url 'rand' %}"> Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/notfound.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}


{% block body %}
    

    <div>
        <h1>No such content exist</h1>
    </div>

{% endblock %}

encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}


{% block body %}
    <h1>All Related Searches</h1>

    <ul>
        {% for entry in entries %}
        
        <a href="{% url 'content' TITLE=entry %}"> <li>{{ entry }}</li> </a> 



        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/showcontent.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}


{% block body %}
    

    <div>
        {{ content | safe }}
        <!-- {% autoescape off %}
        {{ entries }}
        {% endautoescape %} -->
    </div>
    <p><a href="{% url 'edit' TITLE=title %}">Edit Page</a></p>

{% endblock %}